[workspace]
members = [
    "server",
    "proto_gen"
]
resolver = "2"

[workspace.dependencies]
prost = "0.12.3"
prost-types = "0.12.3"
bytes = "1.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
